INSERT INTO ssm.role_module (role_id, module_id) VALUES (100, 1);
INSERT INTO ssm.role_module (role_id, module_id) VALUES (100, 2);
INSERT INTO ssm.role_module (role_id, module_id) VALUES (200, 3);
INSERT INTO ssm.role_module (role_id, module_id) VALUES (200, 4);
INSERT INTO ssm.role_module (role_id, module_id) VALUES (200, 5);
INSERT INTO ssm.role_module (role_id, module_id) VALUES (200, 6);
INSERT INTO ssm.role_module (role_id, module_id) VALUES (300, 7);
INSERT INTO ssm.role_module (role_id, module_id) VALUES (400, 1);
INSERT INTO ssm.role_module (role_id, module_id) VALUES (500, 2);